name: Django CI

on:
  push:
    branches:
    - master
    - development
    - main

  pull_request:
    branches: 
    - master
    - development
    - main
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install pre commit & Bandit
      run: |
        pip install bandit
        pip install pre-commit
    - name: Run Bandit
      run: bandit -r . -ll --confidence-level LOW,MEDIUM

    - name: Run Tests
      run: |
        python manage.py test
